site_name: FHI HelseID Tools
theme:
  name: readthedocs
  logo: logo_small.webp
  features:
  custom_dir: docs/overrides

plugins:
    - mkdocs-jupyter
    - search
    - mermaid2
extra_css:
   - overrides/readthedocs.css
   - overrides/cards.css