# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: HelseId.Tools.CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Display dotnet version
      run: dotnet --version
      
    - name: Restore dependencies
      run: dotnet restore --runtime win-x64
      
    - name: Build
      run: dotnet build --no-restore --configuration Release --verbosity minimal

    - name: Run test
      run: dotnet test --no-build --configuration Release --verbosity normal