name: Publish NuGet Package
description: |
  This workflow packs and publishes the NuGet package for the HelseId.Tools project
  when a new release is created.

on:
  workflow_dispatch:
  release:
    types: [created]  

jobs:

  publish-nuget:
    runs-on: ubuntu-latest
    # Only run when a release is created
    if: github.event_name == 'release'
    steps:
    - uses: actions/checkout@v4
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Extract version from tag
      run: |
        echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Pack NuGet package
      run: |
        dotnet pack ./src/Fhi.HelseIdSelvbetjening.CLI/Fhi.HelseIdSelvbetjening.CLI.csproj \
        --configuration Release \
        -p:PackageVersion=${{ env.VERSION }} \
        --output nuget-packages

    - name: Publish NuGet package
      run: dotnet nuget push ./nuget-packages/*.nupkg --api-key ${{ secrets.NUGET_ORG_FHI_PUBLISH }} --source https://api.nuget.org/v3/index.json
      if: github.event_name == 'release'

    - name: Upload NuGet Package Artifact
      uses: actions/upload-artifact@v4
      with:
        name: nuget-package
        path: nuget-packages/*.nupkg
        retention-days: 7

  
